"""new fields in user model

Revision ID: b4dd26285c88
Revises: f9bc53193c31
Create Date: 2018-08-29 12:30:58.816375

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b4dd26285c88'
down_revision = 'f9bc53193c31'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('image', sa.BLOB(), nullable=True))
    # ### end Alembic commands ###
