"""new fields in user model

Revision ID: e0fbdea51d63
Revises: 2109c25d44f5
Create Date: 2018-08-10 14:43:19.747852

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e0fbdea51d63'
down_revision = '2109c25d44f5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('interests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sports', sa.Boolean(), nullable=True),
    sa.Column('games', sa.Boolean(), nullable=True),
    sa.Column('dancing', sa.Boolean(), nullable=True),
    sa.Column('travel', sa.Boolean(), nullable=True),
    sa.Column('cinema', sa.Boolean(), nullable=True),
    sa.Column('music', sa.Boolean(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('user', sa.Column('about_me', sa.String(length=140), nullable=True))
    op.add_column('user', sa.Column('age', sa.Integer(), nullable=True))
    op.add_column('user', sa.Column('gender', sa.String(length=6), nullable=True))
    op.add_column('user', sa.Column('name', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_user_gender'), 'user', ['gender'], unique=False)
    op.create_index(op.f('ix_user_name'), 'user', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_name'), table_name='user')
    op.drop_index(op.f('ix_user_gender'), table_name='user')
    op.drop_column('user', 'name')
    op.drop_column('user', 'gender')
    op.drop_column('user', 'age')
    op.drop_column('user', 'about_me')
    op.drop_table('interests')
    # ### end Alembic commands ###
